name: Scheduled Playwright Tests

on:
  schedule:
    - cron: '30 2 * * 1-5'  # MON - FRI 8:00 AM IST
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install
      - name: Set environment variable
        run: echo "ENV=prod" >> $GITHUB_ENV
      - name: Run Playwright tests
        run: npx playwright test --with-deps
      - name: Generate HTML report with metadata
        run: npm run report
      - name: Zip the report folder
        run: zip -r playwright-report.zip playwright-report
      - name: Upload zipped report artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-zip
          path: playwright-report.zip
          retention-days: 30
      - name: Send zipped report via email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: satzmails90@gmail.com
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "📊 Playwright Test Report - $(date +'%Y-%m-%d')"
          to: satztesting1990@gmail.com
          from: satzmails90@gmail.com
          body: |
            Hello,
            Please find attached the zipped Playwright test report including charts, screenshots, and videos.

            Metadata:
            - Browser: Chromium
            - Platform: Ubuntu 20.04
            - Environment: Production
            - Execution Time: $(date +'%T')

            Regards,
            Playwright Automation Bot
          attachments: playwright-report.zip